"""
Django settings for messaging_app project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see:
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see:
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os


# ---------------------------------
# Base Directory
# ---------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent


# ---------------------------------
# SECURITY
# ---------------------------------
SECRET_KEY = 'django-insecure-zp+3^kij6xt=)@+g$j3gs1)uml5tu+a8%@)a7jcxw*y4t6=cuc'
DEBUG = True
ALLOWED_HOSTS = []


# ---------------------------------
# APPLICATIONS
# ---------------------------------
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party
    'rest_framework',
    'django_filters',
    'rest_framework.authtoken',

    # Local App
    'chats',
]


# ---------------------------------
# MIDDLEWARE
# ---------------------------------
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    # Custom Middleware
    'chats.middleware.RequestLoggingMiddleware',
]


# ---------------------------------
# CUSTOM USER MODEL
# ---------------------------------
AUTH_USER_MODEL = 'chats.User'


# ---------------------------------
# DJANGO REST FRAMEWORK
# ---------------------------------
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],

    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],

    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
    ],

    'DEFAULT_PAGINATION_CLASS': 'chats.pagination.MessagePagination',
    'PAGE_SIZE': 20,
}


# ---------------------------------
# SIMPLE JWT
# ---------------------------------
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
}


# ---------------------------------
# URLS / WSGI
# ---------------------------------
ROOT_URLCONF = 'messaging_app.urls'
WSGI_APPLICATION = 'messaging_app.wsgi.application'


# ---------------------------------
# TEMPLATES
# ---------------------------------
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,

        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# ---------------------------------
# DATABASE
# ---------------------------------
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# ---------------------------------
# PASSWORD VALIDATION
# ---------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# ---------------------------------
# INTERNATIONALIZATION
# ---------------------------------
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# ---------------------------------
# STATIC FILES
# ---------------------------------
STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'


# ---------------------------------
# DEFAULT AUTO FIELD
# ---------------------------------
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
LOG_FILE_PATH = os.path.join(BASE_DIR, "request_logs.log")

